# Generated by Django 4.1 on 2022-09-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_curso_creacion_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteAut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=200)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
