# Generated by Django 4.1 on 2022-09-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_articulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=100)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('Articulo', models.ManyToManyField(to='home.articulo')),
                ('Estudiante', models.ManyToManyField(to='home.estudiante')),
            ],
        ),
    ]
